language: node_js
node_js:
- '6'
before_script:
- npm install -g grunt-cli
sudo: false
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: KHiUlljcNzcx8hPuyDYDuIGj79Xj3v2eonF/SraJ2lSkrhv+l/RGEsctFrnha6+zRN5adP8ugJ7eD4Z990hb40wWgJIP11RwKheHpz8gBeyvdtYI4FI+1FcLE6X0bvzVaj7FhSQbLS6lLIy74ZMQJsuAWPH8N7PLlov6YlRatRQ=
  on:
    tags: true
    repo: noflo/noflo-runtime
